from .CarbonateFracFactors import CarbonateFracFactorDeines1974

from .MethaneBioFracFactors import MethaneBioFracFactorFixed
from .MethaneBioFracFactors import MethaneBioFracFactorUniform
from .MethaneBioFracFactors import MethaneBioFracFactorGropp
